export const GET_CATEGORIES = 'GET_CATEGORIES';
export const UPDATE_FORM = 'UPDATE_FORM';
export const SUBMIT_FILTERS = 'SUBMIT_FILTERS';
export const RESET_FILTERS = 'RESET_FILTERS';
export const EXPORT_PRODUCTS = 'EXPORT_PRODUCTS';
