export const GET_PRODUCT_CHARACTERISTICS = 'GET_PRODUCT_CHARACTERISTICS';
export const GET_PRODUCT_LOGS = 'GET_PRODUCT_LOGS';
export const GET_PRODUCT_COMMENTS = 'GET_PRODUCT_COMMENTS';
export const UPDATE_PRODUCT = 'UPDATE_PRODUCT';
export const ADD_PRODUCT_COMMENT = 'ADD_PRODUCT_COMMENT';
export const GET_COMMENTS_GROUPS = 'GET_COMMENTS_GROUPS';
