export const UPLOAD_FILE = 'UPLOAD_FILE';
export const UPDATE_BY_FILE = 'UPDATE_BY_FILE';
export const SET_COLUMN_HANDLER = 'SET_COLUMN_HANDLER';
export const REMOVE_COLUMN_HANDLER = 'REMOVE_COLUMN_HANDLER';
export const UPDATE_FORM = 'UPDATE_FORM';
export const RESET_FORM = 'RESET_FORM';
export const RESET_COLUMN_HANDLERS = 'RESET_COLUMN_HANDLERS';
