export const UPLOAD_FILE_VALUE = 'UPLOAD_FILE_VALUE';
export const SET_COLUMNS_HANDLERS = 'SET_COLUMNS_HANDLERS';
export const UPDATE_COLUMNS_HANDLERS = 'UPDATE_COLUMNS_HANDLERS';
export const UPDATE_FORM_VALUE = 'UPDATE_FORM_VALUE';
export const RESET_FORM_VALUE = 'RESET_FORM_VALUE';
