export const GET_PRODUCTS = 'GET_PRODUCTS';
export const UPDATE_TABLE = 'UPDATE_TABLE';
export const REGENERATE_PRICE_PRODUCT = 'REGENERATE_PRICE_PRODUCT';
export const UPDATE_PRODUCT_ITEM = 'UPDATE_PRODUCT_ITEM';
